version: "3.9"

services:
  iptv_restream_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_STREAM_DELAY: 18
        VITE_STREAM_PROXY_DELAY: 30
        # Set VITE_BACKEND_URL to the backend's URL if it's on a different host
        # VITE_BACKEND_URL: http://backend:5000
    ports:
      - "3000:80" # Expose frontend on port 3000
    networks:
      - app-network

  iptv_restream_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - streams_data:/streams
      - channels:/channels
    environment:
      STORAGE_PATH: /streams/
      # BACKEND_URL: http://localhost:5000 # Optional override
    ports:
      - "5000:5000" # Expose backend on port 5000
    networks:
      - app-network

volumes:
  streams_data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  channels:

networks:
  app-network:
    driver: bridge
